version: '3'

services:
  pathway:
    build: 
      context: demo-question-answering
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Cache:/app/Cache
      - ./paper-source/data:/app/data

  paper:
    depends_on:
      - pathway
    build: 
      context: paper-source
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./paper-source/data:/app/data
    environment:
      - PATHWAY_HOST=pathway
      - PATHWAY_PORT=8000
    command: ["sh", "-c", "sleep 10 && streamlit run --server.port 8501 --server.enableCORS false scrape.py"]
